version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g @angular/cli
      - npm install

  build:
    commands:
      
      - npm run build 

artifacts:
  base-directory: dist/angular-build   # <-- replace with your real folder name
  files:
    - '**/*'
