name: Clone Private Repo

on:
  push:
    branches:
      - master

jobs:
  clone:
    runs-on: self-hosted

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Clone private repo
        run: |
          git clone https://kanchana08:${{ secrets.TESTING }}@github.com/kanchana08/angular.git

      - name: Run commands in cloned repo
        run: |
          cd github_actions
          ls -la
          echo "Current directory: $(pwd)"
          npm install
          npm run  build --prod
